### ISSUE TITLE
[Issue] Contrast between colors in documentation is not colorblind-friendly

### ISSUE THREAD

**Issue by jmcastagnetto** [devOpifex/g2r#1]
**Describe the bug**

The reduced contrast of dark over dark colors, makes it difficult to read the documentation, in particular for colorblind people.

**Reproducible Example**

![image](https://user-images.githubusercontent.com/364668/109429927-89f8b800-79cc-11eb-8537-9d3c0c72bfa9.png)

**Possible solution**

Either use better contrasting colors, or allow for theme change in the docs.

**Comment by jmcastagnetto** [comment]
I find useful this Firefox extension: https://addons.mozilla.org/en-US/firefox/addon/let-s-get-color-blind/

(even with that extension corrections, it is hard to read)

**Comment by JohnCoene** [comment]
Sorry about this. I tried to have the site pick up site user system default (dark vs. light theme) but the dark theme is perhaps not great, I've turned this off until I figure a better way.

<kbd>CTRL</kbd> | <kbd>CMD</kbd> + <kbd>SHIFT</kbd> + <kbd>R</kbd> should now clear the cache and switch you to light theme.
