### ISSUE TITLE
Several legends in symmetrical plot

### ISSUE THREAD

**Issue by b-rodrigues** [devOpifex/g2r#10]
Hello,

I was wondering if it was possible to use symmetric intervals to create something like this plot: [https://i.imgur.com/AnPoNdm.png](https://i.imgur.com/AnPoNdm.png)

Here is my attempt:

```r
library(forcats)
library(dplyr)
library(g2r)

data("gss_cat")

gss_cat %>%
  filter(marital %in% c("Married", "Divorced"),
         relig %in% c("Catholic", "Jewish")) %>%  
  group_by(marital, relig, rincome) %>%
  summarise(total = sum(tvhours, na.rm = TRUE)) %>%
  g2(asp(y = total, x = relig, color = rincome)) %>%
  fig_interval(adjust(type = "dodge", margin = 0)) %>%
  planes(~marital, type = "mirror")
```

This kinda works, but there is no way of knowing what marital status the first half of the graph is. It is likely "Divorced", as per alphabetical order. Would there be a way of solving this issue? Maybe have a different shade of colors for each half of the graph?

**Comment by b-rodrigues** [comment]
I thought maybe about adding the level of `marital` to the tooltip, so the tooltip would show the values of `relig`, `total` and `marital`, but I can’t figure out how to add the level of `marital` to the tooltip either.

**Comment by JohnCoene** [comment]
I think it's there, it's just well hidden due to poor defaults.

```r
gss_cat %>%
  filter(marital %in% c("Married", "Divorced"),
         relig %in% c("Catholic", "Jewish")) %>%  
  group_by(marital, relig, rincome) %>%
  summarise(total = sum(tvhours, na.rm = TRUE)) %>%
  g2(asp(y = total, x = relig, color = rincome)) %>%
  fig_interval(adjust(type = "dodge", margin = 0)) %>%
  planes(~marital, type = "mirror") %>% 
  motif(padding = 100L) # add padding
```

**Comment by b-rodrigues** [comment]
Great, this solves the issue! Many thanks for your prompt reply!

**Comment by JohnCoene** [comment]
Pleasure. Note that you can pass a vector: `motif(padding = c(10, 70, 20, 30L))` for different padding per side
