### ISSUE TITLE
planes()

### ISSUE THREAD

**Issue by jordancampbell23** [devOpifex/g2r#6]
**Description**
Hi John, 

Trying to get a facet that appears vertically opposed to horizontally--and wanted to see if that was possible. 

Thanks for your time!

**Example**

```r
library(g2r)

g2(iris, asp(Sepal.Width, color = Species)) |>
  fig_density() |>
  planes(
    ~Species,
    type = "matrix",
    cols = 1,
    rows = 3
  )
```

**Comment by JohnCoene** [comment]
Like this?

```r
library(g2r)

g2(iris, asp(Sepal.Width, color = Species)) |>
  fig_density() |>
  planes(
    ~Species,
    type = "list",
    cols = 1,
    rows = 3
  )
```

**Comment by jordancampbell23** [comment]
Yeah, that was easy. I mistakenly assumed from the example that "list" was unstructured.

**Comment by JohnCoene** [comment]
It's not on you. The main pain point of g2.js is the documentation or lack thereof.
